# Generated by Django 4.0.3 on 2022-04-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('cost_price', models.FloatField(blank=True, default=0, verbose_name='Себестоимость')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Цена')),
                ('amount', models.FloatField(blank=True, default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
    ]
