# Generated by Django 4.0.3 on 2022-11-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма'),
        ),
    ]
